name: ${artifactId}
version: ${version}
main: ${main.class}
permissions:
  c4.admin:
    description: Allows administration of Connect4.
    default: op
commands:
  c4:
    description: Connect4 administration commands.
    permission: c4.admin
    usage: /c4
    aliases: connect4